title: Ian Sheridan's Art
email: ian.sheridan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm <span class="name">Ian Sheridan</span> and I have Parkinson's Disease
  (PD). ppp is the most significant influence on my art. Creating artwork
  makes gives me a deep sense of satisfaction. I'm inspired by the works of
  Ilan Katin, a Berlin-based artist, Vincent Van Gogh, Jackson Pollock, Keith
  Haring, Bob Ross, and Pete Draws.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iansheridan.art" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iansheridan
github_username:  iansheridan


# Build settings

# theme: minima

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - raw_images
  - generate_portfolio.rb

sass:
    sass_dir: _sass

