# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Ian Sheridan's Art"
name: "Ian Sheridan"
email: ian.sheridan@gmail.com
description: "The art of Ian Sheridan"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iansheridan.art" # the base hostname & protocol for your site
cover: /img/og.png
logo: /img/emojis/technologist.png
resume: /20170529_ian-sheridan_resume.pdf
twitter_url: https://twitter.com/iansheridan
instagram_url: https://instagram.com/iansheridan
github_url: https://github.com/iansheridan

markdown: kramdown

collections:
  gallery:
    output: true

sass:
  sass_dir: _scss

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'packag*.json'
  - 'yarn.lock'
  - '*.config.js'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins:
  - github-pages
  - jekyll-postcss

postcss:
  cache: false
