---
title: Ian Sheridan's Art
name: Ian Sheridan
email: ian.sheridan@gmail.com
description: The art of Ian Sheridan
baseurl: ""
url: https://iansheridan.art
cover: /img/og.png
logo: /img/emojis/technologist.png
resume: /20170529_ian-sheridan_resume.pdf
twitter_url: https://twitter.com/iansheridan
instagram_url: https://instagram.com/iansheridan
github_url: https://github.com/iansheridan
markdown: kramdown
collections:
  gallery:
    output: true
sass:
  sass_dir: _scss
exclude:
  - Gemfile
  - Gemfile.lock
  - "*.gemspec"
  - README.md
  - node_modules
  - build
  - packag*.json
  - yarn.lock
  - "*.config.js"
  - raw_images
keep_files:
  - CNAME
  - .git
  - .gitignore
plugins:
  - github-pages
  - jekyll-postcss
postcss:
  cache: false

