# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: [Ian Sheridan]
name: Ian Sheridan
email: ian.sheridan@gmail.com
description: [The art of Ian Sheridan]
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iansheridan.art" # the base hostname & protocol for your site
twitter_username: iansheridan
github_username:  iansheridan

gems: [jekyll-paginate]
permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'solar-theme-jekyll-master']

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Build settings
markdown: kramdown
